import express from "express";
const authRouter = express.Router();
import { createUser, checkUser, resetPassword } from "../controllers/userController.js";
import auth from '../middleware/auth.js';
import { generateInviteCode, listInviteCodes, revokeInviteCode } from '../controllers/inviteController.js';

/**
 * @openapi
 * /api/auth/register:
 *   post:
 *     summary: Register a new user (invite-only)
 *     tags:
 *       - Auth
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               username:
 *                 type: string
 *               email:
 *                 type: string
 *               password:
 *                 type: string
 *               inviteCode:
 *                 type: string
 *     responses:
 *       201:
 *         description: Created
 *       400:
 *         description: Bad Request
 *       401:
 *         description: Invalid invite code
 */

authRouter.post('/register', createUser);
authRouter.post('/login', checkUser);

authRouter.post('/logout', auth, (_req, res) => res.status(204).send());
authRouter.post('/forgot-password', resetPassword);

authRouter.post('/invite-code', generateInviteCode);
authRouter.get('/invite-codes', auth, listInviteCodes);
authRouter.delete('/invite-codes/:code', auth, revokeInviteCode);

/**
 * @openapi
 * /api/auth/login:
 *   post:
 *     summary: Log in a user
 *     tags: [Auth]
 *     security: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               identifier:
 *                 type: string
 *               password:
 *                 type: string
 *     responses:
 *       200:
 *         description: OK
 *       401:
 *         description: Invalid credentials
 */

/**
 * @openapi
 * /api/auth/logout:
 *   post:
 *     summary: Logout current user
 *     tags: [Auth]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       204:
 *         description: No Content
 *       401:
 *         description: Not authenticated
 */

/**
 * @openapi
 * /api/auth/forgot-password:
 *   post:
 *     summary: Request a password reset
 *     tags: [Auth]
 *     security: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               email:
 *                 type: string
 *     responses:
 *       200:
 *         description: Reset link sent!
 *       404:
 *         description: Email not found!
 */

/**
 * @openapi
 * /api/auth/invite-code:
 *   post:
 *     summary: Generate a new invite code
 *     tags: [Auth]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               intendedFor:
 *                 type: string
 *     responses:
 *       201:
 *         description: Created
 *       401:
 *         description: Not authenticated
 */

/**
 * @openapi
 * /api/auth/invite-codes:
 *   get:
 *     summary: List invite codes generated by current user
 *     tags: [Auth]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: OK
 *       401:
 *         description: Not authenticated
 */

/**
 * @openapi
 * /api/auth/invite-codes/{code}:
 *   delete:
 *     summary: Revoke an unused invite code
 *     tags: [Auth]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: code
 *         required: true
 *         schema:
 *           type: string
 *     responses:
 *       204:
 *         description: No Content
 *       404:
 *         description: Invite code not found
 *       400:
 *         description: Invite code already used
 *       401:
 *         description: Not authenticated
 */

export default authRouter;
